name: main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-msvc-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest

    # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly
    # As used here, the Developer Command Prompt created is targeting x64 and using the default the Windows SDK
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Configure and build tests
      run: |
        cmake --preset windows-msvc-debug
        cmake --build --preset windows-msvc-debug

    - name: Run tests
      working-directory: ${{github.workspace}}/out/build/windows-msvc-debug/test
      run: ./Debug/rtc_test.exe --gtest_brief=1 --gtest_also_run_disabled_tests
      shell: bash

  windows-x64-Release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest

    # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly
    # As used here, the Developer Command Prompt created is targeting x64 and using the default the Windows SDK
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Configure and build no-tests
      run: |
        cmake --preset windows-msvc-release
        cmake --build --preset windows-msvc-release
