name: main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-x64-Debug-Test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure and build tests
      run: |
        cmake -preset test
        cmake --build --preset x64-Debug-Test
    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest --preset x64-Debug-Test --output-on-failure
  windows-x64-Release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure and build no-tests
      run: |
        cmake --preset no-test
        cmake --build --preset x64-Release
